import { useRouter } from "next/router";
import Head from "next/head";

export async function getStaticProps() {
  const res = await fetch(`https://jsonplaceholder.typicode.com/posts`);
  const posts = await res.json();

  if (!posts) {
    return {
      notFound: true,
    };
  }

  return {
    props: { posts },
  };
}

const Posts = ({ posts }) => {
  const router = useRouter();

  const move = (id) => {
    router.push(`/Posts/${id}`);
  };

  return (
    <div style={{ margin: "15px" }}>
      <Head>
        <title>next app | Posts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>posts</h1>
      <hr />
      {posts.map((post) => {
        return (
          <div
            style={{ cursor: "pointer" }}
            onClick={() => move(post.id)}
            key={post.id}
            style={{ borderBottom: "1px solid black" }}
          >
            <h2 style={{ cursor: "pointer" }}> - {post.title}</h2>
            <p style={{ cursor: "pointer" }}>{post.body}</p>
          </div>
        );
      })}
    </div>
  );
};

export default Posts;
