import Head from "next/head";

const About = () => {
  return (
    <>
      <Head>
        <title>next app | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>About</h1>
    </>
  );
};

export default About;
