import Head from "next/head";

const Contact = () => {
  return (
    <>
      <Head>
        <title>next app | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>contact</h1>
    </>
  );
};

export default Contact;
